### ISSUE TITLE
ShouldReloadEveryTime

### ISSUE THREAD

**Issue by jjercx** [kenneth1003/react-render-ctrl#1]
Hi, I dont understand the ShouldReloadEveryTime in your render flow. I only see subtrees are in reverse order, but to me, they will behave the same for the final user. Am I missing something?

**Comment by kenneth1003** [comment]
Sorry for the late reply!
I am recently busy with something else, so I didn't notice the message.
The reversed order matters because,

when `ShouldReloadEveryTime` is true
- For more time sensitive data, if you already have data in you state, it still won't render until the latest fetching is over. 

when `ShouldReloadEveryTime` is false
- For less time sensitive data, if you already have data in you state it will just render it directly.

I hope it explains the point.
Thanks!
